config/routes.rb
Rails.application.routes.draw do
  root to: "firstlists#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/sign_in/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :firstlists do
    member do
      get "auto_select"
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firstlist.rb
class Firstlist < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title, presence: { message: "タイトルを入力してください"}
    validates :text1, presence: { message: "リスト１を入力してください"}
  end

  # def self.auto_select
  # end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable
  
  has_many :firstlists

  with_options presence: true do
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)\w{6,}\z/.freeze
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :nickname,length: { maximum: 8 }
    validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    
    with_options on: :create do
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: "半角6文字以上で英字と数字の両方を含めて設定してください" }
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲストユーザー"
      # user.confirmed_at = Time.now  # Confirmable を使用する場合は必要
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :nickname])
  end

end

app/controllers/firstlists_controller.rb
class FirstlistsController < ApplicationController
  before_action :set_firstlist, except: [:index, :new, :create]
  
  def index
    @firstlists = Firstlist.where(user_id: current_user )
  end

  def new
    @firstlist = Firstlist.new
  end

  def create
    @firstlist = Firstlist.new(firstlist_params)
  if @firstlist.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @firstlist.update(firstlist_params)
      redirect_to firstlist_path(@firstlist)
    else
      render :edit
    end
  end

  def destroy
    if @firstlist.destroy
      redirect_to action: :index 
    end
  end

  def auto_select
    @firstlist = Firstlist.find(params[:id])
    #あとでbefore_actionにする
  end

  private

  def firstlist_params
    params.require(:firstlist).permit(:title, :text1, :text2, :text3, :text4, :text5, :text6).merge(user_id: current_user.id)
  end

  def set_firstlist
    @firstlist = Firstlist.find(params[:id])
  end
  
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: [:destroy, :update]

  def check_guest
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの変更・削除はできません"
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firstlists_helper.rb
module FirstlistsHelper
end

app/views/firstlist/index.erb
<div class="main_display">

<%# 左側のメニュー %>
<div class="left_menu">
  <%= link_to "my List-list", "#", class: "side-list1" %>
  <%= link_to "知ってほしいこと", "#", class: "side-list2" %>
  <%= link_to "みんなのList-list", "#", class: "side-list3" %>
  <%= link_to "アカウント情報", "#", class: "side-list4" %>
</div>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">
  <h2 class="menu-title">my List-list</h2>

  <% @firstlists.each do |item| %>
  <li class='list-table'>      <%= link_to hoge_path(hoge.id) do %>
    <%= link_to "@firstlist.title", "#", class: "main-list" %>
      </li>

    <% end %>
  <% end %>
  <%# リストがない場合のダミー %>
  <% if @firstlists.empty? %>
  <li class='list-table'>
    <%= link_to "休日のそうじ", "#", class: "main-list" %>
    <%= link_to "勉強前にすること", "#", class: "main-list" %>
    <%= link_to "休憩にすること", "#", class: "main-list" %>
    <%= link_to "外食", "#", class: "main-list" %>
    <%= link_to "校正確認", "#", class: "main-list" %>
    <%= link_to "寝る前にすること", "#", class: "main-list" %>
  </li>
  <%end%>
  <%# リストがない場合のダミー %>



  </div>
</div>

<%# 右側のメニュー %>
<div class="right_menu">
  <%= link_to "新規リスト", new_firstlist_path, class: "right-list1" %>
  <%= link_to "並び替え", "#", class: "right-list2" %>
</div>

</div>

app/views/firstlists/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/firstlists/_left_menu.erb
<div class="left_menu">
  <%= link_to "my List-list", firstlists_path, class: "side-list1" %>
  <%= link_to "知ってほしいこと(未実装)", "#", class: "side-list2" %>
  <%= link_to "みんなのList-list(未実装)", "#", class: "side-list3" %>
  <%= link_to "アカウント情報(未実装)", "#", class: "side-list4" %>
</div>

app/views/firstlists/_left_menu.html.erb
<div class="left_menu">
  <%= link_to "my List-list", firstlists_path, class: "side-list1" %>
  <%= link_to "知ってほしいこと(未実装)", "#", class: "side-list2" %>
  <%= link_to "みんなのList-list(未実装)", "#", class: "side-list3" %>
  <%= link_to "アカウント情報", edit_user_registration_path, class: "side-list4" %>
</div> 

app/views/firstlists/auto_select.html.erb
<div class="main_display">

<%# 左側のメニュー %>
<%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
<div class="bg_image">

<div class='firstlist-table'> 
  <div  class = "firstlist-title">
    <%= "AUTO SELECT" %>
  </div>

  <div  class = "auto-select-copy">
    <%= "結果はコレ！" %>
  </div>

  <div  class = "firstlist-list" >
    <% i = 0 %>
    <% while i == 0 %>
      <% num = rand(1..6) %>
      <% if num == 1 %>
        <% unless @firstlist.text1 == "" %>
          <%= "#{@firstlist.text1}" %>
          <% i = 1 %>
          <% else %>
          <% i = 0 %>
        <% end %>
      <% elsif num == 2 %>
        <% unless @firstlist.text2 == "" %>
          <%= "#{@firstlist.text2}" %>
          <% i = 1 %>
          <% else %>
          <% i = 0 %>
        <% end %>
      <% elsif num == 3 %>
        <% unless @firstlist.text3 == "" %>
          <%= "#{@firstlist.text3}" %>
          <% i = 1 %>
          <% else %>
          <% i = 0 %>
        <% end %>
      <% elsif num == 4 %>
        <% unless @firstlist.text4 == "" %>
          <%= "#{@firstlist.text4}" %>
          <% i = 1 %>
          <% else %>
        <% end %>
      <% elsif num == 5 %>
        <% unless @firstlist.text5 == "" %>
          <%= "#{@firstlist.text5}" %>
          <% i = 1 %>
          <% else %>
          <% i = 0 %>
        <% end %>
      <% elsif num == 6 %>
        <% unless @firstlist.text6 == "" %>
          <%= "#{@firstlist.text6}" %>
          <% i = 1 %>
          <% else %>
          <% i = 0 %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

</div>
</div>

<%# 右側のメニュー %>
<div class="right_menu">
<%= link_to "戻る", :back, class: "right-list1" %>
<%= link_to "もう一回！", auto_select_firstlist_path, class: "auto-select-box" %>
</div>

</div>

app/views/firstlists/edit.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">

<%# 入力フォーム %>
    <%= form_with(model: @firstlist, local: true) do |f| %>
    <%#= render 'shared/error_messages', model: @firstlist %>
    
     <li class='new-form'>
      <%= f.text_field :title, class:"firstlist-form", id:"firstlist-form", placeholder:"リストタイトル（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text1, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト１（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text2, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト２（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text3, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト３（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text4, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト４（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text5, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト５（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text6, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト６（20文字以内）", maxlength:"20" %>
      <%= f.submit "登録する", class: "submit-btn" %>
    </li>
    <% end %>
<%# /入力フォーム %>

  </div> <%# この２行をendの下に移動させなければいけない %>
</div>
<%# /メインメニュー %>


<%# 右側のメニュー %>
    <div class="right_menu">
      <%= link_to "このリストを削除する", firstlist_path, method: :delete, class: "right-list1" %>
    </div>

app/views/firstlists/edit.html.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">

<%# 入力フォーム %>
    <%= form_with(model: @firstlist, local: true) do |f| %>
    <%= render 'error_messages', model: @firstlist %>

     <div class='new-form'>
      <%= f.text_field :title, class:"firstlist-form-title", id:"firstlist-form", placeholder:"リストタイトル（20文字以内）※必須", maxlength:"20" %>
      <%= f.text_field :text1, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト１（20文字以内）※必須", maxlength:"20" %>
      <%= f.text_field :text2, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト２（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text3, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト３（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text4, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト４（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text5, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト５（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text6, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト６（20文字以内）", maxlength:"20" %>
      <%= f.submit "登録する", class: "submit-btn" %>
    </div>
    
    <% end %>
<%# /入力フォーム %>

  </div> <%# この２行をendの下に移動させなければいけない %>
</div>
<%# /メインメニュー %>

<%# 右側のメニュー %>
    <div class="right_menu">
      <%= link_to "戻る", :back, class: "right-list1" %>
      <%= link_to "このリストを削除する", firstlist_path,data: { confirm: "本当に削除しますか？" }, method: :delete, class: "right-list2" %>
    </div>

app/views/firstlists/index.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">
  <h2 class="menu-title">my List-list</h2>

  <li class='list-table'> 
    <% list_count = 0 %> <%# ※1 %>
    <% @firstlists.each do |firstlist| %>
      <%= link_to "#{firstlist.title}", firstlist_path(firstlist), class: "main-list" %>
      <% list_count += 1 %>
    <% end %>
    <%# ※1.以下 listの合計が奇数の場合、最後の列が中央配置になってしまう。それを避けるため、見えないリストを挿入している %>
      <% if list_count % 2 == 1 %>
      <div class="main-list-hidden"></div>
      <% end %>
  </li>
  
  <%# リストがない場合のダミー %>
  <% if @firstlists.empty? %>
  <li class='list-table'>
    <%= link_to "休日のそうじ", "#", class: "main-list" %>
    <%= link_to "勉強前にすること", "#", class: "main-list" %>
    <%= link_to "休憩にすること", "#", class: "main-list" %>
    <%= link_to "外食", "#", class: "main-list" %>
    <%= link_to "校正確認", "#", class: "main-list" %>
    <%= link_to "寝る前にすること", "#", class: "main-list" %>
  </li>
  <%end%>
  <%# リストがない場合のダミー %>

  </div>
</div>

<%# 右側のメニュー %>
<div class="right_menu">
  <%= link_to "新規リスト", new_firstlist_path, class: "right-list1" %>
  <%= link_to "並び替え（未実装）", "#", class: "right-list2" %>
</div>

</div>

app/views/firstlists/index.html.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">
  <h2 class="menu-title">my List-list</h2>
  
<ul>
  <li class='list-table'> 
    <% list_count = 0 %> <%# ※1 %>
    <% @firstlists.each do |firstlist| %>
      <%= link_to "#{firstlist.title}", firstlist_path(firstlist), class: "main-list" %>
      <% list_count += 1 %>
    <% end %>
    <%# ※1 以下 listの合計が奇数の場合、最後の列が中央配置になってしまう。それを避けるため、見えないリストを挿入している %>
      <% if list_count % 2 == 1 %>
      <div class="main-list-hidden"></div>
      <% end %>
  </li>
  </ul>
  
  <%# リストがない場合のダミー %>
  <% if @firstlists.empty? %>
  <div class='list-table'>
    <%= link_to "普段の行動を", "#", class: "main-list" %>
    <%= link_to "リストで整理しよう！", "#", class: "main-list" %>
    <%= link_to "『新規リスト』から", "#", class: "main-list" %>
    <%= link_to "リストを作成してね！", "#", class: "main-list" %>
    <%= link_to "例：寝る前にすること", "#", class: "main-list" %>
    <%= link_to "例：休日の掃除", "#", class: "main-list" %>
  </div>
  <%end%>
  <%# リストがない場合のダミー %>

  </div>
</div>

<%# 右側のメニュー %>
<div class="right_menu">
  <%= link_to "新規リスト", new_firstlist_path, class: "right-list1" %>
  <%#= link_to "並び替え（未実装）", "#", class: "right-list2" %>
</div>

</div>

app/views/firstlists/new.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">

<%# 入力フォーム %>
    <%= form_with(model: @firstlist, local: true) do |f| %>
    <%#= render 'shared/error_messages', model: @firstlist %>
    
     <li class='new-form'>
      <%= f.text_field :title, class:"firstlist-form", id:"firstlist-form", placeholder:"リストタイトル（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text1, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト１（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text2, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト２（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text3, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト３（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text4, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト４（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text5, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト５（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text6, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト６（20文字以内）", maxlength:"20" %>
      <%= f.submit "登録する", class: "submit-btn" %>
    </li>
    <% end %>

  </div>
</div>
<%# /メインメニュー %>


<%# 右側のメニュー %>
<div class="right_menu">

</div>

<%# /入力フォーム %>

</div>

app/views/firstlists/new.html.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">

<%# 入力フォーム %>
    <%= form_with(model: @firstlist, local: true) do |f| %>
    <%= render 'error_messages', model: @firstlist %>
    
     <div class='new-form'>
      <%= f.text_field :title, class:"firstlist-form-title", id:"firstlist-form", placeholder:"リストタイトル（20文字以内）※必須", maxlength:"20" %>
      <%= f.text_field :text1, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト１（20文字以内）※必須", maxlength:"20" %>
      <%= f.text_field :text2, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト２（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text3, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト３（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text4, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト４（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text5, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト５（20文字以内）", maxlength:"20" %>
      <%= f.text_field :text6, class:"firstlist-form", id:"firstlist-form", placeholder:"リスト６（20文字以内）", maxlength:"20" %>
      <%= f.submit "登録する", class: "submit-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%# /メインメニュー %>

<%# 右側のメニュー %>
<div class="right_menu">
  <%= link_to "戻る", :back, class: "right-list1" %>
</div>

<%# /入力フォーム %>
</div>

app/views/firstlists/show.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">

  <li class='firstlist-table'> 
    <%= link_to "#{@firstlist.title}", "#", class: "firstlist-title" %>
    <% if @firstlist.text1.present? %>
      <%= link_to "#{@firstlist.text1}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text2.present? %>
      <%= link_to "#{@firstlist.text2}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text3.present? %>
      <%= link_to "#{@firstlist.text3}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text4.present? %>
      <%= link_to "#{@firstlist.text4}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text5.present? %>
      <%= link_to "#{@firstlist.text5}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text6.present? %>
      <%= link_to "#{@firstlist.text6}", "#", class: "firstlist-list" %>
    <% end %>
  </li>

  </div>
</div>

<%# 右側のメニュー %>
<div class="right_menu">
  <%= link_to "新規リスト", new_firstlist_path, class: "right-list1" %>
  <%= link_to "編集", edit_firstlist_path, class: "right-list2" %>
  <%= link_to "AUTO SELECT※", auto_select_firstlist_path, class: "auto-select-box" %>
</div>

</div>

app/views/firstlists/show.html.erb
<div class="main_display">

<%# 左側のメニュー %>
  <%= render partial: 'left_menu' %>

<%# メインメニュー %>
<div class="main_menu">
  <div class="bg_image">

  <div class='firstlist-table'> 
    <h2 class="firstlist-title">
    <%= "#{@firstlist.title}" %> </h2>

    <% if @firstlist.text1.present? %>
      <%= link_to "#{@firstlist.text1}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text2.present? %>
      <%= link_to "#{@firstlist.text2}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text3.present? %>
      <%= link_to "#{@firstlist.text3}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text4.present? %>
      <%= link_to "#{@firstlist.text4}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text5.present? %>
      <%= link_to "#{@firstlist.text5}", "#", class: "firstlist-list" %>
    <% end %>
    <% if @firstlist.text6.present? %>
      <%= link_to "#{@firstlist.text6}", "#", class: "firstlist-list" %>
    <% end %>
  </div>

  </div>
</div>

<%# 右側のメニュー %>
<div class="right_menu">
  <%= link_to "戻る", root_path, class: "right-list1" %>
  <%= link_to "新規リスト", new_firstlist_path, class: "right-list2" %>
  <%= link_to "編集", edit_firstlist_path, class: "right-list3" %>
  <%= link_to "AUTO SELECT", auto_select_firstlist_path, class: "auto-select-box" %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

<body>
  <header class="header">
  <div class="header-left">
    <%= link_to image_tag("header_logo.png", class:"header-logo"), firstlists_path %>
  </div>
  <div class="header-right">

  <% if user_signed_in? %>
    <ul class="login-lists">
        <li><%= link_to current_user.nickname, edit_user_registration_path, class: "user-nickname" %> </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout_btn" %> </li>
    </ul>
    <% else %>
    <ul class="login-lists">
      <li><%= link_to "ログイン", new_user_session_path, class: "log-in-btn" %></li>
      <li><%= link_to "新規登録", new_user_registration_path, class: "sign-up-btn" %></li>
    </ul>
    <% end %>
  </div>
  </header>


  <%= yield %>

  <footer>
    <p>
      Copyright list-list 2020.
    </p>
  </footer>
  
</body>
</html>